# Generated by Django 2.0.6 on 2018-06-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberTurns', models.IntegerField()),
                ('numberTeams', models.IntegerField()),
                ('probabilityInjuries', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('continent', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceleration', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('force', models.IntegerField()),
                ('captain', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('lastName', models.CharField(max_length=70)),
                ('record', models.CharField(max_length=70)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Country')),
                ('feature', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('config', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Config')),
            ],
        ),
        migrations.CreateModel(
            name='Stadistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winningTeam', models.CharField(max_length=120)),
                ('record', models.CharField(max_length=120)),
                ('fastRunner', models.CharField(max_length=120)),
                ('injureds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('numberRunners', models.IntegerField()),
                ('simulation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Simulation')),
            ],
        ),
        migrations.AddField(
            model_name='simulation',
            name='stadistic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Stadistic'),
        ),
        migrations.AddField(
            model_name='runner',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Team'),
        ),
    ]
