# Generated by Django 2.0.6 on 2018-06-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_auto_20180623_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='time',
        ),
    ]
